---
# This is a role for setting up the client.

- name: Create alias for st
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.0.2 st'

- name: Create alias for gw
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.0.3 gw'


- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/user/passlist.txt
    owner: user
    mode: 0644

...
